name: SimpleCICD_CD
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 1234 
      source: #Revati014.Folder (128)
      trigger:
        branches:
          include:
            - main
            - Prasanna
            - SCGCP

pool:
  name: SelfHosted
  demands:
    - Agent.Name -equals Agennt

stages:
- stage: RunStage
  jobs:
  - job: RunJob
    steps:
    - script: echo "🎯 Simple stage is running!"
      displayName: 'Print Hello Message'
