name: SimpleCICD_CD
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: Revati014_CICD  # Alias for the CI pipeline
      source: githubci  # The actual CI pipeline name in Azure DevOps
      trigger:
        branches:
          include:
            - main              # Trigger CD when CI completes on main

pool:
  name: SelfHosted
  demands:
    - Agent.Name -equals Agennt

steps:
# ✅ Checkout the 'prasanna' branch
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 1
  ref: refs/heads/prasanna

# ✅ Run a script that exists in the 'prasanna' branch
- script: |
    echo "🌿 Now running from branch: prasanna"
    echo "📄 Executing prasanna_script.sh..."
    bash prasanna_script.sh
  displayName: 'Run deployment script from prasanna branch'
