name: SimpleCICD_CD
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 1234 
      source: Revati014.Folder
      trigger:
        branches:
          include:
            - main

pool:
  name: SelfHosted
  demands:
    - Agent.Name -equals Agennt

#steps:
# Explicitly checkout the 'prasanna' branch
#- checkout: self
#  persistCredentials: true
 # fetchDepth: 1
  #ref: refs/heads/prasanna

# Run script that exists in 'prasanna' branch
#- script: |
   # echo "Running script from 'prasanna' branch"
 #   bash prasanna_script.sh
#  displayName: 'Run prasanna_script.sh from prasanna branch'
