name: SimpleCICD_CD
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: Revati014_CICD  
      source: Revati014.Folder  
      trigger:
        branches:
          include:
            - main
            - SimpleCICD_CD
        paths:
          include:
            - A/B/C/D/*         

pool:
  name: SelfHosted
  demands:
    - Agent.Name -equals Agennt

steps:
- task: CmdLine@2
  displayName: 'Run Command Line Script'
  inputs:
    script: |
      echo Write your commands here
      echo Hello world

- task: PowerShell@2
  displayName: 'Print Date and Time'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Current Date and Time: $(Get-Date)"
